# Topics
## 1. Matrix Manipulation in Python
## 2. Relaxation Method and the Laplace Equation.


## 1. Matrix Manipulation in Python

In [5]:
'''Important:

For most purposes, 

M = np.matrix([[1., 1.5, 3.],
              [-1., 11., -1.],
              [0., -1., 10.]])

and

M = np.array([[1., 1.5, 3.],
              [-1., 11., -1.],
              [0., -1., 10.]])

give you the same thing.  But certain matrix methods don't apply to a numpy array 
(such as the inverse; note: .I and .getI() both give you the inverse.).

For the whole list of methods:

http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

or do 

>>> dir(M)

'''

import numpy as np
M1 = np.matrix([[1., 1.5, 3.],
              [-1., 11., -1.],
              [0., -1., 10.]])

M2 = np.matrix([[10., 1., 2.],
              [1., 1., 4.3],
              [2., -1., 10.]])

a = np.array([1., 2., 3.])
b = np.array([1., 1/2., 1/3.])

M_sum = a + b
print 'M_sum', M_sum

# np.dot
# for 1D -- dot product
dot_product = np.dot(a, b)
print 'dot_product:', dot_product



M_sum [ 2.          2.5         3.33333333]
dot_product: 3.0


In [2]:
# Note: attributes are listed first, before the dunder (special) methods.
print dir(M1)

['A', 'A1', 'H', 'I', 'T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_wrap__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__delslice__', '__dict__', '__div__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__hex__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__oct__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__rep

In [6]:
# for 2D -- matrix multiplication
M_multip = np.dot(M1, M2)
print 'M_multip:'
print M_multip

# another example of matrix multiplication
M1_op_a = np.dot(M1, a)
print 'M1_op_a:'
print M1_op_a

# transpose
M1_T = M1.T
print 'Transposed M1:'
print M1_T

# trace-sum of diagonals
print 'M1_trace', M1.trace()

# inverse
print 'M1_inverse:' 
print M1.I
print '...to verify (M1*M1_inverse):'
# Note: for most python operations, the numerical error is on the level of 1e-16.
print np.dot(M1.I, M1)

M_multip:
[[ 17.5   -0.5   38.45]
 [ -1.    11.    35.3 ]
 [ 19.   -11.    95.7 ]]
M1_op_a:
[[ 13.  18.  28.]]
Transposed M1:
[[  1.   -1.    0. ]
 [  1.5  11.   -1. ]
 [  3.   -1.   10. ]]
M1_trace [[ 22.]]
M1_inverse:
[[ 0.85826772 -0.14173228 -0.27165354]
 [ 0.07874016  0.07874016 -0.01574803]
 [ 0.00787402  0.00787402  0.0984252 ]]
...to verify (M1*M1_inverse):
[[  1.00000000e+00   0.00000000e+00   4.44089210e-16]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [7]:
# To get the determinant
import numpy.linalg as LA
import numpy as np
M1 = np.matrix([[1., 1.5, 3.],
              [-1., 11., -1.],
              [0., -1., 10.]])
print "Determinant of M1", LA.det(M1)

Determinant of M1 127.0


## Quick Breakout

### Write a function, solve_eqn() that solves the following matrix equations.  You should catch the expected exception of a non-invertible matrix.

### Mx = b

### A) 
M1 = np.matrix([[1., 1.5, 3.],[-1., 11., -1.],[0., -1., 10.]]) and b = np.array([1., 1/2., 1/3.])

### B) 
M2 = np.matrix([[1.,0., 0.],[-2., 0., 0.],[4., 6., 1.]]) and c = np.array([1., 2., 3.])

### C) 
M3 = np.matrix([[1., 1.5, 3.],[-1., 11., -1.],[0., -1., 10.]]) and d = np.array([1., 2., 3.])

In [8]:
def solve_eqn(M, b):
    try:
        M.I
    except:
        raise Exception('You suck')
    else: 
        return np.dot(M.I, b)

In [9]:
M1 = np.matrix([[1., 1.5, 3.],[-1., 10., -1.],[0., -1., 10.]]) 
b = np.array([1., 1/2., 1/3.])
soln = solve_eqn(M1, b)
print 'Solution:', soln

Solution: [[ 0.67948718  0.12250712  0.04558405]]


In [10]:
M2 = np.matrix([[1.,0., 0.],[-2., 0., 0.],[4., 6., 1.]]) 
c = np.array([1., 2., 3.])
soln = solve_eqn(M2, c)
print 'Solution:', soln

Exception: You suck

In [11]:
M3 = np.matrix([[-3. , -5., 1.], [9. ,14., 1.],  [18., 29., -2.]])
d = np.array([3., 2., 1.])
soln = solve_eqn(M3, d)
print 'Solution:', soln
# print M2.I
# print LA.det(M2)

Solution: [[  1.52121587e+16  -9.60767921e+15  -2.40191980e+15]]


## 2. Relaxation Method and the Laplace Equation.


### The name, "Relaxation Method":

### For example, for the diffusion equation, an initial temperature distribution u(x, t) "relaxes" to an equilibrium solution as t -> inf.

(See Numerical Recipes 3rd. Ed. p. 1059)

## Relaxation Methods: The Jacobi Method
### Solving a linear set of equations

In [ ]:
'''

The Jacobi Method: The matrix approach.
You can also use for loop

This cell is copied verbatim from last class (wk7-2)

'''


import numpy as np

max_iter = 100

# initialize the matrix
A = np.array([[10., -1., 2., 0.],
              [-1., 11., -1., 3.],
              [2., -1., 10., -1.],
              [0.0, 3., -1., 8.]])

D = np.diag(A)
print "The diagonal elements:\n", D
print "The diagonal matrix:\n", np.diagflat(D)
R = A - np.diagflat(D)
print "The remainder matrix:\n", R

# initialize the RHS vector
b = np.array([6., 25., -11., 15.])


# prints the linear system
print("System of Linear Equations:")
for i in range(A.shape[0]):
    row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
    print " + ".join(row) + "=" + str(b[i])
print '\n\n'

# Initial Guess: Usually you would want an "educated" guess, 
# typcially x_guess = D^(-1)b. 
# But because the method is so robust, it hardly matters...
# We will try all 0's and a set of random numbers.
x = np.zeros(b.shape)
#x = np.random.rand(b.shape[0])
# specify tolerance
tol = 1e-4

counter = 0
print 'Starting Jacobi method iterations...'
while counter < max_iter:
    print "Iteration {:d}:{}".format(counter, x)
    # Just to create a numpy array that has the same dimension as x.
    x_new = np.empty(x.shape)

    for i in range(A.shape[0]):
        # np.dot computes dot product
        
        s = np.dot(R[i,], x)
        x_new[i] = (b[i] - s) / A[i, i]
            
    counter += 1      
    # Returns True if two arrays are element-wise equal within a tolerance.
    if np.allclose(x, x_new, rtol=tol):
        print 'Tolerance achieved.  Printing results...'
        break      
    else:
        if counter == max_iter:
            raise Exception('max_iter exceeded!')

    x = x_new

print '\n\n'
print "Solution:", x 
print "Estimated Error:", (np.dot(A, x) - b)/b 

## Relaxation Methods: The Laplace Equation


More at http://en.wikipedia.org/wiki/Relaxation_(iterative_method)

In [ ]:
%matplotlib inline
'''

Jacobi Method: the for-loop approach -- 1D example.

Note how the initial guess of all zeros over a number of iterations "relaxes" to the final solution -- not unlike
an initial temperature distribution relaxes to the steady-state distribution (solution).

'''



import numpy as np
import matplotlib.pyplot as plt

NX = 11

#initialization
V = np.zeros(NX)


#Boundary Conditions:
V[NX-1] = 1.
V[0] = 0
maxdiff = 1e-6
diff = 1
x = np.arange(NX)

while diff > maxdiff:
    diff = 0.         #crucial!!
    # start from 1 and end at NX-2: because you don't want to change the BC!!
    for i in range(1, NX-1):    
        newV = (V[i-1]+V[i+1])/2
        prev_diff = abs(newV - V[i])
        # to find the maximum difference in each loop (going over all interior points).
        V[i] = newV
        if diff < prev_diff:    
            diff = prev_diff
  
            
print V
plt.plot(x, V)
plt.show()
          

## The Physics:
### This corresponds to the electric potential of a parallel plate capacitor 
### (length, width >> thickness)

## Breakout Problem:
### For a long rectangular tube, the potential on two opposite sides = 1 volt, and the potential on the other two sides = 0.  
### Write a program to find V(x, y) in the interior of the tube.   Start with (2x2) interior grid points.
### Then plot the result as a surface plot.

## Connection between the "2-for-loop" way and the matrix way -- go to slides.

## Breakout Problem:

### Write a function, jacobi_meth() that takes two positional argument A and b.  It should also take max_iter, tol, and x_guess as keyword argument.  Set the default values as such: max_iter = 100, tol = 1e-6, and the default value of x_guess should be a zero vector.   Finally inside each iteration, no loops allowed.

### Apply this function to the Laplace Equation problem.

### Using the answer we obtained before (for the system of algebraic equations) as the doctest.

## Breakout Solution: See jacobi_meth.py

## End of week 8-1